
services:
  backend:
    build: ./backend
    image: revleet_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  
  frontend:
    build: ./frontend
    image: revleet_frontend
    ports:
      - "5173:5173"



